export const trendingData = [
  { repo_name: 'llama.cpp', author: 'ggerganov', language: 'C++', stars: 75000, forks: 10800, description: 'Port of Meta LLaMA model in C/C++', topic: 'LLM' },
  { repo_name: 'ollama', author: 'ollama', language: 'Go', stars: 82000, forks: 6500, description: 'Get up and running with Llama 3, Mistral, Gemma 2', topic: 'LLM' },
  { repo_name: 'vllm', author: 'vllm-project', language: 'Python', stars: 28000, forks: 4200, description: 'High-throughput and memory-efficient LLM serving engine', topic: 'LLM' },
  { repo_name: 'litellm', author: 'BerriAI', language: 'Python', stars: 14000, forks: 1800, description: 'Call all LLM APIs using OpenAI format', topic: 'LLM' },
  { repo_name: 'text-generation-webui', author: 'oobabooga', language: 'Python', stars: 42000, forks: 5500, description: 'Gradio web UI for Large Language Models', topic: 'LLM' },
  { repo_name: 'gpt4all', author: 'nomic-ai', language: 'C++', stars: 68000, forks: 7400, description: 'Run powerful LLMs locally on CPU and GPU', topic: 'LLM' },
  { repo_name: 'segment-anything', author: 'facebookresearch', language: 'Python', stars: 47000, forks: 5800, description: 'Segment Anything Model by Meta AI', topic: 'Computer Vision' },
  { repo_name: 'ultralytics', author: 'ultralytics', language: 'Python', stars: 36000, forks: 7200, description: 'Ultralytics YOLO11 for state-of-the-art object detection', topic: 'Computer Vision' },
  { repo_name: 'florence-2', author: 'microsoft', language: 'Python', stars: 12000, forks: 1400, description: 'Florence-2: Advancing a Unified Representation for Vision', topic: 'Computer Vision' },
  { repo_name: 'depth-anything', author: 'LiheYoung', language: 'Python', stars: 8500, forks: 890, description: 'Depth Anything: Unleashing the Power of Monocular Depth Estimation', topic: 'Computer Vision' },
  { repo_name: 'stable-diffusion-webui', author: 'AUTOMATIC1111', language: 'Python', stars: 145000, forks: 27000, description: 'Stable Diffusion web UI', topic: 'Computer Vision' },
  { repo_name: 'ComfyUI', author: 'comfyanonymous', language: 'Python', stars: 58000, forks: 6200, description: 'Powerful and modular stable diffusion GUI', topic: 'Computer Vision' },
  { repo_name: 'mlflow', author: 'mlflow', language: 'Python', stars: 18000, forks: 3900, description: 'Open source platform for the machine learning lifecycle', topic: 'MLOps' },
  { repo_name: 'dvc', author: 'iterative', language: 'Python', stars: 13000, forks: 1200, description: 'ML Experiments Management with Git', topic: 'MLOps' },
  { repo_name: 'prefect', author: 'PrefectHQ', language: 'Python', stars: 15000, forks: 1500, description: 'Workflow orchestration tool empowering data engineers', topic: 'MLOps' },
  { repo_name: 'evidently', author: 'evidentlyai', language: 'Python', stars: 5500, forks: 890, description: 'Evaluate and monitor ML models in production', topic: 'MLOps' },
  { repo_name: 'bentoml', author: 'bentoml', language: 'Python', stars: 7200, forks: 820, description: 'Build Production-Grade AI Applications', topic: 'MLOps' },
  { repo_name: 'zenml', author: 'zenml-io', language: 'Python', stars: 3800, forks: 420, description: 'ZenML: The open-source MLOps framework for reproducible pipelines', topic: 'MLOps' },
  { repo_name: 'autogen', author: 'microsoft', language: 'Python', stars: 35000, forks: 5100, description: 'Framework for multi-agent AI application development', topic: 'Agents' },
  { repo_name: 'crewai', author: 'crewAIInc', language: 'Python', stars: 22000, forks: 3100, description: 'Framework for orchestrating role-playing AI agents', topic: 'Agents' },
  { repo_name: 'langchain', author: 'langchain-ai', language: 'Python', stars: 96000, forks: 15800, description: 'Building applications with LLMs through composability', topic: 'Agents' },
  { repo_name: 'smolagents', author: 'huggingface', language: 'Python', stars: 16000, forks: 1900, description: 'Agents that think in Python and run it to tackle tasks', topic: 'Agents' },
  { repo_name: 'swarm', author: 'openai', language: 'Python', stars: 18000, forks: 2200, description: 'Educational framework for lightweight multi-agent orchestration', topic: 'Agents' },
  { repo_name: 'phidata', author: 'phidatahq', language: 'Python', stars: 12000, forks: 1400, description: 'Build multi-modal Agents with memory, knowledge and tools', topic: 'Agents' },
  { repo_name: 'polars', author: 'pola-rs', language: 'Rust', stars: 30000, forks: 1900, description: 'Dataframes powered by multithreaded vectorized query engine', topic: 'Data Tools' },
  { repo_name: 'duckdb', author: 'duckdb', language: 'C++', stars: 24000, forks: 1800, description: 'In-process analytical SQL database management system', topic: 'Data Tools' },
  { repo_name: 'great-expectations', author: 'great-expectations', language: 'Python', stars: 9800, forks: 1500, description: 'Data quality validation for Python workflows', topic: 'Data Tools' },
  { repo_name: 'pandas-ai', author: 'Sinaptik-AI', language: 'Python', stars: 13000, forks: 1400, description: 'Chat with your database using natural language', topic: 'Data Tools' },
  { repo_name: 'marimo', author: 'marimo-team', language: 'Python', stars: 8200, forks: 320, description: 'A reactive Python notebook with no hidden state', topic: 'Data Tools' },
  { repo_name: 'lancedb', author: 'lancedb', language: 'Python', stars: 5600, forks: 390, description: 'Developer-friendly serverless vector database for AI', topic: 'Data Tools' },
]
